project:
  type: website
  output-dir: "docs"

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Pratik Majumdar"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/PratikMJ004
      - icon: linkedin
        href: https://www.linkedin.com/in/pratik-majumdar-491282216/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

